POST http://localhost:4000/posts/createNewPost
Content-Type: application/json

{
    "postId":12
}
###
GET http://localhost:4000/posts/getAllPosts
###
GET http://localhost:4000/posts/getPostId
###
POST http://localhost:4000/posts/deletePost
Content-Type: application/json

{
    "postId":"45"
}

