POST http://localhost:4000/posts/createNewPost
Content-Type: application/json

{
    "postId":12
}
###
GET http://localhost:4000/posts/getAllPosts
###
GET http://localhost:4000/posts/getPostId
###
POST http://localhost:4000/posts/deletePost
Content-Type: application/json

{
    "postId":"45"
}
###
POST http://localhost:4000/posts/likePost
Content-Type: application/json

{
    "PostId":"6666906bd06a5385918c3f5a"
}
###
POST http://localhost:4000/posts/postComment
Content-Type: application/json

{
    "PostId":"6666906bd06a5385918c3f5a",
    "comment":"Hi this is for testing comments functionality",
    "userName":"goutham"
}