GET http://localhost:4000
###
POST http://localhost:4000/users/createUser
Content-Type: application/json

{
    "userName":"reddy",
    "email":"reddy@mdp",
    "password":"123",
    "state":"telangana",
    "city":"khammam",
    "DateOfBirth":"10-06-2004",
    "gender":"male",
    "interests":[],
    "profilePicture":"",
    "DateAccountCreated":"",
    "Profession":"",
    "EducationalQualifications":[],
    "friends":[],
    "data2":"",
    "data3":""
}
###
GET http://localhost:4000/users/getAllUsers
###
POST http://localhost:4000/users/checkUserName
Content-Type: application/json

{
    "userName":"reddy"
}
###
POSt http://localhost:4000/users/getPassword
Content-Type: application/json

{
    "userName":"GouthAm"
}
###
POST http://localhost:4000/users/checkLoginCredentials
Content-Type: application/json

{
    "userName":"GohAm",
    "password":"123"
}
###
POST http://localhost:4000/users/getUserNameByEmailID
Content-Type: application/json

{
    "email":"gouth@gmail.com"
}
###
POST http://localhost:4000/users/getNonFriends
Content-Type: application/json

{
    "userName":"goutham"
}